---
- name: Create traefik network
  community.docker.docker_network:
    name: traefik
    state: present
    driver: overlay
    attachable: true

- name: Deploy Swarmpit app service
  community.docker.docker_swarm_service:
    name: app
    image: swarmpit/swarmpit:1.9
    env:
      SWARMPIT_DB: "http://db:5984"
      SWARMPIT_INFLUXDB: "http://influxdb:8086"
    mounts:
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
        read_only: yes
    networks:
      - name: traefik
    resources:
      limits:
        memory: 1024M
      reservations:
        memory: 512M
    placement:
      constraints:
        - "node.role == manager"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.swarmpit-rtr.entrypoints=websecure"
      - "traefik.http.routers.swarmpit-rtr.rule=Host(`swarmpit.{{ root_domain }}`)"
      - "traefik.http.routers.swarmpit-rtr.middlewares=authelia"
      - "traefik.http.routers.swarmpit-rtr.service=swarmpit-svc"
      - "traefik.http.services.swarmpit-svc.loadbalancer.server.port=8080"
      - "traefik.constraint=proxy-public"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 60s
      timeout: 10s
      retries: 3
    state: present

- name: Deploy CouchDB service
  community.docker.docker_swarm_service:
    name: db
    image: treehouses/couchdb:2.3.1
    mounts:
      - source: db-data
        target: /opt/couchdb/data
        type: volume
    networks:
      - name: traefik
    resources:
      limits:
        memory: 256M
      reservations:
        memory: 128M
    state: present

- name: Deploy InfluxDB service
  community.docker.docker_swarm_service:
    name: influxdb
    image: influxdb:1.8
    mounts:
      - source: influx-data
        target: /var/lib/influxdb
        type: volume
    networks:
      - name: traefik
    resources:
      limits:
        memory: 256M
      reservations:
        memory: 128M
    state: present

- name: Deploy Swarmpit agent service
  community.docker.docker_swarm_service:
    name: agent
    image: swarmpit/agent:2.2
    mounts:
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
        read_only: yes
    networks:
      - name: traefik
    deploy_mode: global
    labels:
      swarmpit.agent: 'true'
    resources:
      limits:
        memory: 64M
      reservations:
        memory: 32M
    state: present

vars:
root_domain: yourdomain.com

volumes:
db-data:
  driver: local
influx-data:
  driver: local

- name: Deploy Swarmpit on Docker Swarm - Worker Nodes
hosts: worker_nodes
become: true
tasks:
- name: Join worker nodes to Swarm
  community.docker.docker_swarm:
    state: join
    join_token: "{{ hostvars['manager_nodes']['join_token'] }}"
    remote_addrs: "{{ hostvars['manager_nodes']['manager_ip'] }}"

- name: Create volumes
  community.docker.docker_volume:
    name: db-data
    state: present

- name: Create volumes
  community.docker.docker_volume:
    name: influx-data
    state: present
