---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0775"
  with_items:
    - "{{ docker_syncthing.bulk_data_root }}"
    - "{{ docker_syncthing.config }}"

- name: Create and start container
  community.docker.docker_swarm_service:
    name: syncthing
    image: "{{ docker_syncthing.image }}"
    mounts:
      - source: "{{ docker_syncthing.config }}"
        target: /home/syncthing/.config/syncthing
        type: bind
      - source: "{{ docker_syncthing.bulk_data_root }}"
        target: /var/syncthing
        type: bind
    labels:
      traefik.enable: "true"
      traefik.docker.network: homelab-public

      # Traefik routing for Home Assistant
      traefik.http.routers.syncthing.rule: "Host(`{{ url_syncthing }}`)"
      traefik.http.routers.syncthing.entrypoints: https
      traefik.http.routers.syncthing.tls: "true"
      traefik.http.routers.syncthing.tls.certresolver: letsencrypt

      traefik.http.services.syncthing.loadbalancer.server.port: "8384"

      homepage.group: Tools
      homepage.name: SyncThing
      homepage.icon: syncthing.svg
      homepage.href: https://{{ url_syncthing }}
      homepage.description: Syncthing lets you synchronize your files bidirectionally across multiple devices.
    env:
      TZ: "{{ system_timezone }}"
      PUID: "1000"
      PGID: "1000"
    restart_config:
      condition: any
      delay: 5s
      max_attempts: 3
      window: 120s
    update_config:
      delay: 10s
      order: start-first
      parallelism: 1
    rollback_config:
      parallelism: 0
      order: stop-first
    state: present
    mode: replicated
    placement:
      constraints:
        - node.role == manager
    networks:
      - homelab-public
