---
- name: restart keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted
    daemon_reload: true

- name: reload consul
  ansible.builtin.service:
    name: keepalived
    state: reloaded
    daemon_reload: true
