---
systemd_dir: /etc/systemd/system
config_dir: /etc/default
bin_dir: /usr/local/sbin

wesher_version: v0.2.5
wesher_master: "{{ hostvars[groups['master'][0]]['ansible_facts']['default_ipv6']['address'] }}"
wesher_bind: "{{ ansible_facts['default_ipv6']['address'] }}"
wesher_port: 7000
wesher_subnet: 10.24.0.0/16
wesher_address: "{{ ansible_facts['wg_' + cluster_slug]['ipv4']['address'] }}"

cluster_slug: homelab
wesher_cluster_key: "rAXLmG2tEzgz*sA$Np*$QmBA8SBauKda"
