---
- name: Open ports
  include_role:
    name: ufw_rules
  vars:
    ufw_rules:
      - { rule: allow, port: 5353, proto: tcp, comment: DNS cloudflared }
      - { rule: allow, port: 5353, proto: udp, comment: DNS cloudflared }

