---
# @var docker_apt_gpg_key: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
# The URL of the apt repository's GPG key (Debian/Ubuntu only)
docker_apt_gpg_key: 'https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg'

# @var docker_apt_ignore_key_error: true
# Whether or not to ignore errors when adding the apt repository's GPG key (Debian/Ubuntu only)
docker_apt_ignore_key_error: true

docker_apt_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'armhf' if ansible_architecture == 'armv7l' else 'amd64' }}"

docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"

docker_compose_path: /usr/local/bin/docker-compose

docker_install_compose: true

docker_package: 'docker-ce'

docker_restart_handler_state: restarted

docker_users:
 - "{{ ansible_user }}"