---
docker_version: 26.1.3

docker_install_directory: /usr/bin/
docker_download_url: https://download.docker.com/linux/static/stable/{{ architecture_map[ansible_architecture] }}/docker-{{ docker_version }}.tgz