---
# @var docker_apt_gpg_key: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
# The URL of the apt repository's GPG key (Debian/Ubuntu only)
docker_apt_gpg_key: 'https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg'

# @var docker_apt_ignore_key_error: true
# Whether or not to ignore errors when adding the apt repository's GPG key (Debian/Ubuntu only)
docker_apt_ignore_key_error: true


# @var docker_apt_repository: See defaults/main.yml
# The apt repository to use (Debian/Ubuntu only)
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] {{ https_repository_prefix }}\
  download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} \
  {{ docker_apt_release_channel }}"

# @var docker_compose_path: /usr/local/bin/docker-compose
# The target destination of the `docker-compose` binary that will be installed
docker_compose_path: /usr/local/bin/docker-compose

# @var docker_edition: ce
# Edition can be either `ce` (Community Edition) or `ee` (Enterprise Edition).
docker_edition: ce
# @var docker_install_compose: true
# Whether or not to install `docker-compose`
docker_install_compose: true

# @var docker_package: docker-{{ docker_edition }}
# The name of the Docker package to install
docker_package: 'docker-{{ docker_edition }}'

# @var docker_restart_handler_state: restarted
# The state that the Docker service should assume when a restart event is triggered
docker_restart_handler_state: restarted

# @example #
docker_users:
 - "{{ ansible_user }}"
# @end

# @var https_repository_prefix: https://
# Allows you to customize what the apt repository URL starts with. This is useful if you are using something like
# apt-cacher-ng as a proxy cache which requires the URL to start with http://HTTPS/. (Debian/Ubuntu only)
https_repository_prefix: https://
