---
# - name: Configure UFW
#   ansible.builtin.include_tasks: ufw.yml

- name: Create mount point
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: "0777"
  loop: "{{ export_dirs }}"

- name: Ensure NFS package is installed
  ansible.builtin.package:
    name: nfs-common
    state: present

# - name: Mount NFS share
#   ansible.posix.mount:
#     path: "{{ docker_data_root }}"
#     src: "192.168.2.200:/mnt/storage/homelab"
#     fstype: nfs
#     opts: rw
#     state: mounted

- name: Ensure NFS share is mounted at boot
  ansible.posix.mount:
    path: "{{ item }}"
    src: "192.168.2.200:{{ item }}"
    fstype: nfs
    opts: rw
    state: present
  loop: "{{ export_dirs }}"
