---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0775"
  with_items:
    - "{{ docker_home_assistant.config }}"
    - "{{ docker_home_assistant.data }}"

- name: Copy configuration.yaml
  ansible.builtin.template:
    src: "configuration.yaml.j2"
    dest: "{{ docker_home_assistant.config }}/configuration.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Create and start Home Assistant container
  community.docker.docker_swarm_service:
    name: home_assistant
    image: "{{ docker_home_assistant.image }}"
    networks:
      - homelab-public
    env:
      TZ: "{{ system_timezone }}"
    labels:
      traefik.enable: "true"
      traefik.docker.network: homelab-public

      # Traefik routing for Home Assistant
      traefik.http.routers.homeassistant.rule: "Host(`{{ url_home_assistant }}`)"
      traefik.http.routers.homeassistant.entrypoints: https
      traefik.http.routers.homeassistant.tls: "true"
      traefik.http.routers.homeassistant.tls.certresolver: letsencrypt
      # Authelia Authentication Middleware
      traefik.http.routers.homeassistant.middlewares: auth@swarm

      traefik.http.services.homeassistant.loadbalancer.server.port: "8123"

      homepage.group: Home
      homepage.name: Home Assistant
      homepage.icon: home-assistant
      homepage.href: "https://{{ url_home_assistant }}"
      homepage.description: Home Assistant is free and open-source software used for home automation.
    mounts:
      # - source: home_assistant_config
      #   target: /config
      #   type: volume
      - source: "{{ docker_home_assistant.config }}/configuration.yaml"
        target: /config/configuration.yml
        type: bind
    state: present
    mode: replicated
    placement:
      constraints:
        - node.role == manager
