---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0775"
  with_items:
    - "{{ docker_home_assistant.config }}"
    - "{{ docker_home_assistant.data }}"

- name: Create and start Home Assistant container
  community.docker.docker_swarm_service:
    name: home_assistant
    image: "{{ docker_home_assistant.image }}"
    env:
      TZ: "{{ system_timezone }}"
    labels:
      traefik.enable: "true"
      traefik.docker.network: homelab-public

      # Traefik routing for Home Assistant
      traefik.http.routers.homeassistant.rule: "Host(`{{ url_home_assistant }}`)"
      traefik.http.routers.homeassistant.entrypoints: https
      traefik.http.routers.homeassistant.tls: "true"
      traefik.http.routers.homeassistant.tls.certresolver: letsencrypt
      # Authelia Authentication Middleware
      traefik.http.routers.homeassistant.middlewares: chain-authelia-auth@file

      traefik.http.services.homeassistant.loadbalancer.server.port: "8123"

      homepage.group: Home
      homepage.name: Home Assistant
      homepage.icon: home-assistant
      homepage.href: "https://{{ url_home_assistant }}"
      homepage.description: Home Assistant is free and open-source software used for home automation.
    mounts:
      - source: "{{ docker_home_assistant.config }}"
        target: /config
        type: bind
    restart_config:
      condition: any
      delay: 5s
      max_attempts: 3
      window: 120s
    update_config:
      delay: 10s
      order: start-first
      parallelism: 1
    rollback_config:
      parallelism: 0
      order: stop-first
    state: present
    mode: replicated
    placement:
      constraints:
        - node.role == worker
    networks:
      - homelab-public

- name: Home Assistant Settings Tasks
  ansible.builtin.include_tasks: "settings.yml"

