---
- name: Open ports
  include_role:
    name: ufw_rules
  vars:
    ufw_rules:
      - { rule: allow, port: 50, proto: tcp, from_ip: 192.168.2.0/24, comment: Docker Swarm ESP Encrypted network }
      - { rule: allow, port: 2377, proto: tcp, from_ip: 192.168.2.0/24, comment: Docker Swarm communication with and between manager nodes }
      - { rule: allow, port: 4789, proto: udp, from_ip: 192.168.2.0/24, comment: Docker Swarm overlay network traeffic }
      - { rule: allow, port: 7946, proto: tcp, from_ip: 192.168.2.0/24, comment: Docker Swarm overlay network node discovery }
      - { rule: allow, port: 7946, proto: udp, from_ip: 192.168.2.0/24, comment: Docker Swarm overlay network node discovery }
