---
dirctory_nas_storage: /mnt/shared

docker_root: "{{ nas_storage }}/docker"
docker_data_root: "{{ docker_root }}/data"
docker_config_root: "{{ docker_root }}/config"
bulk_data: "{{ nas_storage }}/bulk_data"
media: "{{ nas_storage }}/media"
media_personal: "{{ nas_storage }}/media/personal"
media_personal_images: "{{ nas_storage }}/media/personal/images"
media_personal_videos: "{{ nas_storage }}/media/personal/videos"
media_images: "{{ nas_storage }}/media/images"
media_movies: "{{ nas_storage }}/media/movies"
media_series: "{{ nas_storage }}/media/series"
backup: "{{ nas_storage }}/backup"
backup_restic: "{{ nas_storage }}/backup/restic"

docker_traefik:
  config: "{{ docker_config_root }}/traefik"
  data: "{{ docker_data_root }}/traefik"
  image: traefik:v3.1.2

docker_authelia:
  config: "{{ docker_config_root }}/authelia"
  image: authelia/authelia:4.38.9
  
docker_cloudflare_ddns:
  image: oznu/cloudflare-ddns:latest

docker_home_assistant:
  config: "{{ docker_config_root }}/home_assistant"
  data: "{{ docker_data_root }}/home_assistant"
  image: homeassistant/home-assistant:2024.7.4

docker_homepage:
  config: "{{ docker_config_root }}/homepage"
  image: ghcr.io/gethomepage/homepage:v0.9.6

docker_bind:
  config: "{{ docker_config_root }}/bind"

docker_pihole:
  config: "{{ docker_config_root }}/pihole"
  data: "{{ docker_data_root }}/pihole"

docker_syncthing:
  config: "{{ docker_config_root }}/syncthing"
  bullk_data: "{{ bulk_data }}/syncthing"
  image: syncthing/syncthing:1.27.9
