---
docker_traefik:
  config: "{{ docker_config_root }}/traefik"
  data: "{{ docker_data_root }}/traefik"
  image: traefik:v3.1.2

docker_authelia:
  config: "{{ docker_config_root }}/authelia"
  image: authelia/authelia:4.38.9
  
docker_cloudflare_ddns:
  image: oznu/cloudflare-ddns:latest

docker_home_assistant:
  config: "{{ docker_config_root }}/home_assistant"
  data: "{{ docker_data_root }}/home_assistant"
  image: homeassistant/home-assistant:2024.7.4

docker_homepage:
  config: "{{ docker_config_root }}/homepage"
  image: ghcr.io/gethomepage/homepage:v0.9.9

docker_bind:
  config: "{{ docker_config_root }}/bind"

docker_pihole:
  config: "{{ docker_config_root }}/pihole"
  data: "{{ docker_data_root }}/pihole"
  image: pihole/pihole:2024.07.0

docker_syncthing:
  config: "{{ docker_config_root }}/syncthing"
  bulk_data: "{{ bulk_data_root }}/syncthing"
  image: syncthing/syncthing:1.27.9

docker_vpn:
  config: "{{ docker_config_root }}/vpn"
  image: qmcgaw/gluetun:v3.38

docker_scrutiny:
  data: "{{ docker_data_root }}/scrutiny"
  influxdb: "{{ docker_database_root }}/influxdb-scrutiny"
  config: "{{ docker_config_root }}/scrutiny"
  image: ghcr.io/analogj/scrutiny:v0.8.1-web
  image_collector: ghcr.io/analogj/scrutiny:v0.8.1-collector
  image_influxdb: arm32v7/influxdb:1.8.10

docker_jellyfin:
  data: "{{ docker_data_root }}/jellyfin"
  config: "{{ docker_config_root }}/jellyfin"
  image: jellyfin/jellyfin:2024090905

docker_swarmpit:
  data: "{{ docker_data_root }}/swarmpit"
  config: "{{ docker_config_root }}/swarmpit"
  database_influxdb: "{{ docker_database_root }}/swarmpit-influxdb"
  database_couchdb: "{{ docker_database_root }}/swarmpit-couchdb"
  image: swarmpit/swarmpit:1.9
  image_collector: ghcr.io/analogj/scrutiny:v0.8.1-collector
  image_influxdb: arm32v7/influxdb:1.8.10
  image_database: treehouses/couchdb:2.3.1
