---

docker_data_root: /mnt/shared/docker/data
docker_config_root: /mnt/shared/docker/config

docker_traefik:
  config: "{{ docker_config_root }}/traefik"
  data: "{{ docker_data_root }}/traefik"
  image: traefik:v3.1.2

docker_authelia:
  config: "{{ docker_config_root }}/authelia"
  image: authelia/authelia:4.38.9
  
docker_cloudflare_ddns:
  image: oznu/cloudflare-ddns:latest

docker_home_assistant:
  config: "{{ docker_config_root }}/home_assistant"
  data: "{{ docker_data_root }}/home_assistant"
  image: homeassistant/home-assistant:2024.7.4

docker_homepage:
  config: "{{ docker_config_root }}/homepage"
  image: ghcr.io/gethomepage/homepage:v0.9.5

docker_bind:
  config: "{{ docker_config_root }}/bind"

docker_pihole:
  config: "{{ docker_config_root }}/pihole"
  data: "{{ docker_data_root }}/pihole"
