---
- name: Open ports
  include_role:
    name: ufw
  vars:
    ufw_rules:
      - { rule: allow, port: 8300, proto: tcp, comment: Consul RPC } # server only
      - { rule: allow, port: 8301, proto: tcp, comment: Consul Serf LAN }
      - { rule: allow, port: 8301, proto: udp, comment: Consul Serf LAN }
      - { rule: allow, port: 8302, proto: tcp, comment: Consul Serf WAN }
      - { rule: allow, port: 8302, proto: udp, comment: Consul Serf WAN }
      - { rule: allow, port: 8500, proto: tcp, comment: Consul UI }
      - { rule: allow, port: 8501, proto: tcp, comment: Consul HTTPS }
      - { rule: allow, port: 8502, proto: tcp, comment: Consul gRPC }
      - { rule: allow, port: 8503, proto: tcp, comment: Consul gRPC TLS }
      - { rule: allow, port: 8600, proto: tcp, comment: Consul DNS }
