---
- name: Create directories
  ansible.builtin.file:
    path: "{{ docker_transmission.config }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0775

- name: Create and start container
  community.docker.docker_container:
    name: transmission
    image: "{{ docker_transmission.image }}"
    network_mode: container:vpn
    pull: yes
    recreate: true
    image_name_mismatch: "recreate"
    volumes:
      - "{{ docker_transmission.config }}:/config"
      - "{{ docker_media_downloads }}:/downloads"
    restart_policy: unless-stopped
    state: started
    labels:
      homepage.group: Download
      homepage.name: Transmission
      homepage.icon: transmission.png
      homepage.href: http://{{ url_prowlarr }}
      homepage.description: Transmission is a very lightweight and simple to use torrent client
      homepage.widget.type: transmission
      homepage.widget.url: http://192.168.2.200:{{ docker_port_transmission_http }}
    env:
      TZ: "{{ system_timezone }}"
      PUID: "1000"
      PGID: "1000"

#- name: VPN Tasks
#  ansible.builtin.include_tasks: "vpn.yml"
