---
- name: Wait for 'services.yaml' to be created
  ansible.builtin.wait_for:
    path: "{{ docker_homepage.config }}/services.yaml"
    state: present

- name: Copy config files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ docker_homepage.config }}/{{ item | basename | regex_replace('.yaml.j2$', '.yaml') }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  with_fileglob:
    - ../templates/*.yaml.j2
