---
restic_version: 0.17.1

restic_download_url: "https://github.com/restic/restic/releases/download/v{{ restic_version }}/restic_{{ restic_version }}_linux_{{ arch[ansible_architecture] }}.bz2"

restic_install_dir: /usr/bin
restic_data_dir: /opt/restic
restic_log_dir: "{{ restic_data_dir }}/log"

restic_systemd_timer_randomizeddelaysec: '4h'
restic_systemd_timer_default_oncalendar: '*-*-* 02:00:00'

arch:
  x86_64: amd64
  aarch64: arm64
  armv7l: arm
