---
- name: Install HAProxy
  ansible.builtin.apt:
    pkg:
      - haproxy
    state: latest
    force_apt_get: true
    update_cache: true

- name: Create HAProxy config file
  ansible.builtin.template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: "0775"

- name: Restart HAProxy service
  ansible.builtin.systemd:
    name: haproxy
    enabled: true
    state: restarted
