---
- name: Open ports
  include_role:
    name: ufw
  vars:
    ufw_rules:
      - { rule: allow, port: 53, proto: tcp, comment: DNS bind }
      - { rule: allow, port: 53, proto: udp, comment: DNS bind }
