services:
  nas:
    container_name: nas
    build:
      context: .
      dockerfile: Dockerfile.debian
    networks:
      cluster_net:
        ipv4_address: 172.18.0.22
    privileged: true
    ports:
      - "2222:22"
    volumes:
      - ./ansible:/ansible
      - disk1:/mnt/disk1
      - disk2:/mnt/disk2
      - disk3:/mnt/disk3
      - disk4:/mnt/disk4
      - disk5:/mnt/disk5
      - disk6:/mnt/disk6

networks:
  cluster_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  disk1:
  disk2:
  disk3:
  disk4:
  disk5:
  disk6: