---
- name: install ufw
  ansible.builtin.apt:
    package: ufw
    state: present

- name: Configure ufw rules
  ansible.builtin.ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    from_ip: "{{ item.from_ip|default('any') }}"
    to_ip: "{{ item.to|default('any') }}"
    comment: "{{ item.comment }}"
  with_items:
    - "{{ ufw_rules }}"
  when: ufw_rules|length > 0
  notify:
    - reload ufw

# - name: Configure ufw redirect rules
#   ansible.builtin.ufw:
#     rule: "{{ item.rule }}"
#     port: "{{ item.port }}"
#     proto: "{{ item.proto }}"
#     from_ip: "{{ item.from_ip|default('any') }}"
#     to_ip: "{{ item.to|default('any') }}"
#     direction: "{{ item.direction }}"
#     comment: "{{ item.comment }}"
#   with_items:
#     - "{{ ufw_redirect_rules }}"
#   when: ufw_redirect_rules|length > 0
#   notify:
#     - reload ufw
#   tags: ufw

- name: enable ufw
  ansible.builtin.ufw:
    state: enabled
