---
- hosts: cluster[0]
  become: true
  # strategy: free
  roles:
    - role: traefik
      tags: [traefik]
    - role: pihole
      tags: [pihole]
    # - role: swarmpit
    #   tags: [swarmpit]
    # - role: resilio
    #   tags: [resilio]
    - role: authelia
      tags: [authelia]
    - role: homepage
      tags: [homepage]
    # - role: cloudflare-ddns
    #   tags: [cloudflare-ddns,cc]
    - role: home-assistant
      tags: [home-assistant,ha,homeassistant]
    - role: syncthing
      tags: [syncthing]
    # - role: scrutiny
    #   tags: [scrutiny]
    # - role: vpn
    #   tags: [vpn]
    # - role: transmission
    #   tags: [transmission]
    # - role: flaresolverr
    #   tags: [flaresolverr]
    # - role: radarr
    #   tags: [radarr]
    # - role: readarr
    #   tags: [readarr]
    # - role: sonarr
    #   tags: [sonarr]
    # - role: bazarr
    #   tags: [bazarr]
    # - role: prowlarr
    #   tags: [prowlarr]
    - role: jellyfin
      tags: [jellyfin]
    # - role: uptime-kuma
    #   tags: [uptime-kuma]
    # - role: glances
    #   tags: [glances]
    # - role: gotify
    #   tags: [gotify]
    # - role: paperless
    #   tags: [paperless]