---
- hosts: cluster
  become: true
  # strategy: free
  roles:
    - role: traefik
      tags: [traefik]
    # - role: swarmpit
    #   tags: [swarmpit]
    - role: authelia
      tags: [authelia]
    - role: cloudflare-ddns
      tags: [cloudflare-ddns,cc]
    - role: home-assistant
      tags: [home-assistant,ha,homeassistant]
    - role: homepage
      tags: [homepage]