---
- hosts: cluster
  become: true
  # strategy: free
  roles:
    - role: bootstrap
      tags: [bootstrap]
    - role: ufw
      tags: [ufw]
    - role: docker
      tags: [docker]
    # - role: wireguard
    #   tags: [wireguard]
    - role: keepalived
      tags: [keepalived]
    - role: consul
      tags: [consul]
    - role: nomad
      tags: [nomad]
    - role: vault
      tags: [vault]
    - role: reboot
      tags: [reboot]
