---
- hosts: cluster
  become: true
  # strategy: free
  roles:
    - role: bootstrap
      tags: [bootstrap]
    - role: prepare_disks
      tags: [disks]
    - role: ufw
      tags: [ufw]
    - role: docker
      tags: [docker]
    - role: docker_swarm
      tags: [docker_swarm]
    # - role: wireguard
    #   tags: [wireguard]
    - role: keepalived
      tags: [keepalived]
    # - role: cloudflared
    #   tags: [cloudflared]
    - role: bind
      tags: [bind]
    - role: lizardfs
      tags: [lizardfs]
    # - role: haproxy
    #   tags: [haproxy]
    # - role: consul
    #   tags: [consul]
    # - role: nomad
    #   tags: [nomad]
    # - role: vault
    #   tags: [vault]
    - role: reboot
      tags: [reboot]
