---
- hosts: cluster
  become: true
  # strategy: free
  roles:
    - role: docker_swarm_app
      vars:
        stack: swarmpit
      tags: [swarmpit]
    - role: docker_swarm_app
      vars:
        stack: traefik
      tags: [traefik]