---
- hosts: cluster
  become: true
  roles:
    - role: bootstrap
      tags: [bootstrap]
    - role: docker
      tags: [docker]
    - role: wireguard
      tags: [wireguard]
    - role: keepalived
      tags: [keepalived]
    - role: consul
      tags: [consul]
    - role: nomad
      tags: [nomad]
    - role: vault
      tags: [vault]
