---
- hosts: cluster[0]
  become: true
  # strategy: free
  roles:
    - role: docker_swarm_app
      vars:
        stack: swarmpit
      tags: [swarmpit]
    - role: traefik
      tags: [traefik]
    - role: authelia
      tags: [authelia]
    - role: cloudflare-companion
      tags: [cloudflare-companion,cc]