---
- hosts: cluster
  become: true
  # strategy: free
  roles:
    - role: docker_swarm_app
      vars:
        stack: swarmpit
      tags: [swarmpit]
    - role: traefik
      tags: [traefik]
    - role: authelia
      tags: [authelia]
    - role: cloudflare-ddns
      tags: [cloudflare-ddns,cc]
    - role: home-assistant
      tags: [home-assistant,ha,homeassistant]