---
- hosts: nas
  become: true
  roles:
    - role: homepage
      tags: [homepage]
    - role: vpn
      tags: [vpn]
    - role: transmission
      tags: [transmission]
    - role: flaresolverr
      tags: [flaresolverr]
    - role: radarr
      tags: [radarr]
    - role: readarr
      tags: [readarr]
    - role: sonarr
      tags: [sonarr]
    - role: bazarr
      tags: [bazarr]
    - role: prowlarr
      tags: [prowlarr]
    - role: directory_export
      tags: [directory_export]
    - role: jellyfin
      tags: [jellyfin]
    - role: scrutiny
      tags: [scrutiny]
    - role: uptime-kuma
      tags: [uptime-kuma]
    - role: glances
      tags: [glances]
    - role: gotify
      tags: [gotify]
    - role: paperless
      tags: [paperless]
    - role: tandoor-recipes
      tags: [tandoor-recipes]
    - role: syncthing
      tags: [syncthing]
    - role: dozzle
      tags: [dozzle]