---
- hosts: nas
  become: true
  roles:
    - role: bootstrap
      tags: [bootstrap]
    - role: ufw
      tags: [ufw]
    - role: docker
      tags: [docker]
    - role: exports_server
      tags: [exports_server]
    # - role: homepage
    #   tags: [homepage]
    # - role: vpn
    #   tags: [vpn]
    # - role: transmission
    #   tags: [transmission]
    # - role: flaresolverr
    #   tags: [flaresolverr]
    # - role: radarr
    #   tags: [radarr]
    # - role: readarr
    #   tags: [readarr]
    # - role: sonarr
    #   tags: [sonarr]
    # - role: bazarr
    #   tags: [bazarr]
    # - role: prowlarr
    #   tags: [prowlarr]
    # - role: directory_export
    #   tags: [directory_export]
    # - role: jellyfin
    #   tags: [jellyfin]
    # - role: scrutiny
    #   tags: [scrutiny]
    # - role: uptime-kuma
    #   tags: [uptime-kuma]
    # - role: glances
    #   tags: [glances]
    # - role: gotify
    #   tags: [gotify]
    # - role: paperless
    #   tags: [paperless]
    # - role: mealie
    #   tags: [mealie]
    - role: restic
      tags: [restic]
    # - role: dozzle
    #   tags: [dozzle]
    # - role: pgadmin
    #   tags: [pgadmin]
    # - role: whats_up_docker
    #   tags: [whats_up_docker]
    # - role: vaultwarden
    #   tags: [vaultwarden]
    # - role: reboot
    #   tags: [reboot]