---
- hosts: vault_cluster
  vars:
    tls_skip_verify: true
    vault_secret_shares: 3
    vault_secret_threshold: 2

  tasks:
    - name: Check if vault is initialized
      ansible.builtin.uri:
        url: http://127.0.0.1:8200/v1/sys/health
        validate_certs: false
        status_code: 200,429,472,501,503
      register: vault_health_response

    - block:
      - name: Initialize vault
        ansible.builtin.uri:
          url: "http://127.0.0.1:8200/v1/sys/init"
          body:
            secret_shares: "{{ vault_secret_shares }}"
            secret_threshold: "{{ vault_secret_threshold }}"
          body_format: json
          method: PUT
          validate_certs: "{{ tls_skip_verify | ternary('false', 'true') }}"
        register: init_vault_response

      - name: Save vault root token and keys
        ansible.builtin.set_fact:
          vault_root_token: "{{ init_vault_response.json.root_token }}"
          vault_keys: "{{ init_vault_response.json.keys_base64 }}"

      - name: Display vault root token
        ansible.builtin.debug:
          msg: "Root Token: {{ vault_root_token }}"

      - name: Display vault keys # separate for pretty printing
        ansible.builtin.debug:
          msg: "Vault keys: {{ vault_keys }}"

      - name: Save bootstrap result
        ansible.builtin.copy:
          content: "{{ vault_root_token }}"
          dest: "./vault_root_token.txt"

      - name: Get vault_root_token.json
        ansible.builtin.fetch:
          src: ./vault_root_token.txt
          dest: ./../../.secrets/.vault_root_token.txt
      no_log: false
      run_once: true
      when:
        - vault_health_response.status == 501

    - name: Check if vault is sealed
      ansible.builtin.uri:
        url: "http://127.0.0.1:8200/v1/sys/health"
        status_code: 200,429,472,501,503
      register: vault_health_response

    - name: Unseal vault
      ansible.builtin.uri:
        url: "http://127.0.0.1:8200/v1/sys/unseal"
        body:
          key: "{{ item }}"
        body_format: json
        method: PUT
      register: unseal_vault_response
      no_log: true
      with_items:
        - "{{ vault_keys }}"
      when:
        - vault_health_response.status == 503
        - vault_health_response.status != 501
        - vault_keys is defined
