---

- name: Download wesher binary x64
  get_url:
      url: "https://github.com/costela/wesher/releases/download/{{ wesher_version }}/wesher-amd64"
      dest: "{{ bin_dir }}/wesher"
      owner: root
      group: root
      mode: 755
  when: ( ansible_facts.architecture == "x86_64" )

- name: Download wesher binary arm64
  get_url:
      url: "https://github.com/rancher/costela/wesher/download/{{ wesher_version }}/wesher-arm64"
      dest: "{{ bin_dir }}/wesher"
      owner: root
      group: root
      mode: 755
  when: ( ansible_facts.architecture is search("arm") )
          and
        ( ansible_facts.userspace_bits == "64" )

