---
- name: Default wesher config
  template:
    src: config.j2
    dest: "{{ config_dir }}/wesher-{{ cluster_slug }}"
    mode: 0660

- name: Wesher service file
  template:
    src: service.j2
    dest: "{{ systemd_dir }}/wesher-{{ cluster_slug }}.service"

- name: Enable the wesher service
  systemd:
    name: "wesher-{{ cluster_slug }}"
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Wait for the wg interface to be up
  wait_for:
    path: "/sys/class/net/wg-{{ cluster_slug }}"
    timeout: 60
    state: present
  when: groups['node']

- name: Update facts after wesher is up
  setup:
