---
# this is the user that has ssh access to these machines
ansible_user: system
ansible_user_pid: 1000
ansible_user_gid: 1000

system_timezone: Europe/Amsterdam

keyboard: pc105
keyboard_layout: us

locale: en_US.UTF-8

locale_options:
# Disable Default (GB) Locale
- regexp: ^ ?en_GB.UTF-8 UTF-8
  line: "# en_GB.UTF-8 UTF-8"
# Enable US Locale
- regexp: "^# ?{{ locale }} UTF-8"
  line: "{{ locale }} UTF-8"

tmp_dir: "{{ x_ansible_download_dir | default(ansible_env.HOME + '/.ansible/tmp') }}"

required_packages:
  - figlet
  - apt-config-auto-update
