---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0775
  with_items:
    - "{{ docker_vpn.config }}"

- name: Create network
  community.docker.docker_network:
    name: media-network
    driver: bridge
    ipam_config:
    - subnet: "{{ docker_subnet }}"
      gateway: "{{ docker_gateway }}"

- name: Create and start container
  community.docker.docker_container:
    name: vpn
    image: "{{ docker_vpn.image }}"
    pull: yes
    recreate: true
    image_name_mismatch: recreate
    restart_policy: unless-stopped
    state: started
    capabilities:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      net.ipv6.conf.all.disable_ipv6: "1"
    volumes:
      - "{{ docker_vpn.config }}:/gluetun"
      - /etc/localtime:/etc/localtime:ro
    networks:
      - name: media-network
    ports:
      - "8888:8888/tcp"
      - "8388:8388/tcp"
      - "8388:8388/udp"
      - "{{ docker_port_prowlarr_http }}:9696"
      - "{{ docker_port_flaresolverr_http }}:8191"
      - "{{ docker_port_radarr_http }}:7878"
      - "{{ docker_port_readarr_http }}:8787"
      - "{{ docker_port_sonarr_http }}:8989"
      # - "{{ docker_port_qbittorrent_http }}:8282"
      # - "{{ docker_port_qbittorrent_other }}:6881/tcp"
      # - "{{ docker_port_qbittorrent_other }}:6881/udp"
      - "{{ docker_port_whisparr_http }}:6969"
      - "{{ docker_port_sabnzbd_http }}:8089"
      - "{{ docker_port_bazarr_http }}:6767"
      - "{{ docker_port_utorrent_http }}:{{ docker_port_utorrent_http }}"
      - "{{ docker_port_utorrent_xmlrpc }}:{{ docker_port_utorrent_xmlrpc }}"
      - "{{ docker_port_utorrent_webdav }}:{{ docker_port_utorrent_webdav }}"
      - "{{ docker_port_utorrent_rt }}:{{ docker_port_utorrent_rt }}"
      - "{{ docker_port_utorrent_dht }}:{{ docker_port_utorrent_dht }}/udp"
    labels:
      homepage.group: Download
      homepage.name: NordVPN
      homepage.icon: nordvpn.png
      homepage.description: Modern web UI for various torrent clients
    env:
      TZ: "{{ system_timezone }}"
      PUID: "{{ ansible_user_pid | int }}"
      PGID: "{{ ansible_user_gid | int }}"
      VPN_SERVICE_PROVIDER: "NordVPN"
      OPENVPN_USER: "{{ secret_vpn_user }}"
      OPENVPN_PASSWORD: "{{ secret_vpn_password }}"
      # SERVER_REGION: ${SERVER_REGION:?err}
      # SERVER_CITIES: ${SERVER_CITIES}
      SERVER_HOSTNAMES: "{{ server_countries }}"
      FIREWALL_OUTBOUND_SUBNETS: "{{ local_subnet }}"
      VPN_TYPE: "openvpn"
      HTTPPROXY: "on"
      SHADOWSOCKS: "on"
      # TOKEN: "{{ nordvpn_token }}"
      # CONNECT: fr765
      # TECHNOLOGY: NordLynx
      # NETWORK: 192.168.2.0/24
      # CHECK_CONNECTION_INTERVAL: "60"
      # DEBUG: trace
