---
- name: Open ports
  include_role:
    name: ufw_rules
  vars:
    ufw_rules:
      - { rule: allow, port: 8200, proto: tcp, from_ip: 192.168.2.0/24, comment: Vault UI }
      - { rule: allow, port: 8201, proto: tcp, from_ip: 192.168.2.0/24, comment: Vault Cluster Addr }
