---
- name: Ensure directory install
  ansible.builtin.file:
    path: "{{ cni_install_dir }}"
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: Install CNI
  ansible.builtin.unarchive:
    src: "{{ cni_zip_url }}"
    dest: "{{ cni_install_dir }}"
    owner: root
    group: root
    remote_src: true
    mode: "0777"
