---
- name: Update apt cache and upgrade
  ansible.builtin.apt:
    update_cache: yes
    upgrade: "yes"

- name: Tailscale Signing Key
  ansible.builtin.apt_key:
    url: https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}.gpg
    state: present

- name: Add Tailscale Deb
  ansible.builtin.apt_repository:
    repo: deb https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} main
    state: present

- name: Install Tailscale
  ansible.builtin.apt:
    name: tailscale
    state: present
    update_cache: yes
  notify: enable tailscaled service

- name: Check if Tailscale is connected
  ansible.builtin.command: tailscale status
  changed_when: false
  register: tailscale_status