---
# @todo Improvement: Complete documentation
# @todo Test: Complete
- name: Include variables based on the operating system
  include_vars: '{{ ansible_os_family }}.yml'

- name: Ensure old versions of Docker are not installed
  become: true
  block:
    - name: Ensure "docker" is not installed
      package:
        name: docker
        state: absent
    - name: Ensure "docker-common" is not installed
      package:
        name: docker-common
        state: absent
    - name: Ensure "docker-engine" is not installed
      package:
        name: docker-engine
        state: absent

- name: Include tasks based on the operating system
  become: true
  block:
    - include_tasks: 'install-{{ ansible_os_family }}.yml'

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

# @action Installs docker-compose
# Installs docker-compose if the `docker_install_compose` variable is set to true.
# docker-compose allows you to configure Docker containers in groups.
- name: Install Docker Compose (based on OS)
  become: true
  block:
    - include_tasks: 'compose-{{ ansible_os_family }}.yml'
  when: docker_install_compose | bool

# @action Adds specified users to docker group
# If the variable `docker_users` is set to an array of usernames then those users
# will be added to the docker group which allows them access to Docker.
- name: Add users to the "docker" group (based on OS)
  become: true
  block:
    - include_tasks: 'users-{{ ansible_os_family }}.yml'
  when: docker_users | length > 0
