---
# roles/docker/tasks/main.yml

- name: Ensure necessary dependencies are installed
  pacman:
    name:
      - tar
      - curl
    state: present
    update_cache: yes

- name: Download Docker tarball
  command: curl -L -o /tmp/docker-20.10.7.tgz https://download.docker.com/linux/static/stable/x86_64/docker-20.10.7.tgz
  register: download_docker
  changed_when: "'/tmp/docker-20.10.7.tgz' in download_docker.stdout"

- name: Extract Docker tarball
  command: tar -xzf /tmp/docker-20.10.7.tgz -C /usr/local/bin --strip-components=1

- name: Set permissions for Docker binaries
  file:
    path: "/usr/local/bin/{{ item }}"
    mode: '0755'
  with_items:
    - docker
    - containerd
    - containerd-shim
    - ctr
    - dockerd
    - docker-init
    - docker-proxy
    - runc

- name: Copy Docker systemd service file
  copy:
    src: docker.service
    dest: /etc/systemd/system/docker.service
    mode: '0644'
  notify:
    - restart docker

- name: Reload systemd daemon to apply Docker service
  systemd:
    daemon_reload: yes

- name: Enable and start Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
