Vagrant.configure("2") do |config|
  config.vm.define "nas-archlinux" do |cfg|
    cfg.vm.box = "archlinux/archlinux"

    # Set the hostname
    cfg.vm.hostname = "nas-archlinux"

    # Configure the static IP
    cfg.vm.network "private_network", ip: "192.168.56.20"

    cfg.vm.provider "virtualbox" do |vb|
      # Set the VM name in VirtualBox
      vb.name = "nas-archlinux"

      # Define the SATA controller
      vb.customize ["storagectl", :id, "--name", "SATAController", "--add", "sata", "--controller", "IntelAHCI"]

      # Adding 6 additional drives
      (1..6).each do |i|
        # Create a second disk (1G)
        disk = "disks/nas-disk-#{i}.vdi"
        unless File.exist? (disk)
          vb.customize ['createhd', '--filename', disk, '--size', 1 * 1024]
        end
        vb.customize ["storageattach", :id, "--storagectl", "SATAController", "--port", i, "--device", 0, "--type", "hdd", "--medium", disk]
      end
    end
  end
end