---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0775"
  with_items:
    - /etc/keepalived
    - /etc/scripts

- name: Show IPs excluding the current host
  debug:
    var: _keepalived_unicast_peers

- name: Install keepalived
  apt:
    name: keepalived
    state: present
    update_cache: true

- name: Create keepalived.conf.service configuration
  ansible.builtin.template:
    src: etc/keepalived/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart keepalived

- name: Copy scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/scripts/{{ item | basename }}"
    owner: root
    group: root
    mode: "0755"
  with_fileglob:
    - ../files/etc/scripts/*
  notify: restart keepalived
