---
- name: Ensure "ip_vs" is added to /etc/modules
  lineinfile:
    path: /etc/modules
    line: "modprobe ip_vs"
    state: present
  # No condition required, it will ensure line is present if not already there

- name: Check if ip_vs module is already loaded
  ansible.builtin.shell: lsmod | grep -w ip_vs
  register: ip_vs_loaded
  ignore_errors: true

- name: Load ip_vs module if not already loaded
  ansible.builtin.command: modprobe ip_vs
  when: ip_vs_loaded.rc != 0

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0775"
  with_items:
    - /etc/keepalived
    - /etc/scripts

- name: Install keepalived
  apt:
    name: keepalived
    state: present
    update_cache: true

- name: Create keepalived.conf.service configuration
  ansible.builtin.template:
    src: etc/keepalived/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart keepalived

- name: Copy scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/scripts/{{ item | basename }}"
    owner: root
    group: root
    mode: "0755"
  with_fileglob:
    - ../files/etc/scripts/*
  notify: restart keepalived
