---
- name: Show IPs excluding the current host
  debug:
    var: _keepalived_unicats_peers

- name: Install keepalived
  apt:
    name: keepalived
    state: present
    update_cache: true

- name: Configure keepalived
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: restart keepalived
