---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0775"
  with_items:
    - "{{ docker_authelia.config }}"

- name: Copy configuration files
  ansible.builtin.template:
    src: "{{ item }}.yml.j2"
    dest: "{{ docker_authelia.config }}/{{ item }}.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  loop:
    - configuration
    - users_database

- name: Create and start Authelia container
  community.docker.docker_swarm_service:
    name: authelia
    image: "{{ docker_authelia.image }}"
    networks:
      - homelab-public
    labels:
      traefik.enable: "true"
      traefik.docker.network: homelab-public
      traefik.http.routers.auth.rule: "Host(`{{ url_authelia }}`)"
      traefik.http.routers.auth.entrypoints: https
      traefik.http.routers.auth.tls: "true"
      traefik.http.routers.auth.tls.certresolver: letsencrypt
      traefik.http.routers.auth.service: auth@swarm
      traefik.http.services.auth.loadbalancer.server.port: "9091"

      homepage.group: Security
      homepage.name: Authelia
      homepage.icon: authelia
      homepage.href: "https://{{ url_authelia }}"
      homepage.description: The Single Sign-On Multi-Factor portal for web apps
    mounts:
      - source: "{{ docker_authelia.config }}"
        target: /config
        type: bind
    restart_config:
      condition: any
      delay: 5s
      max_attempts: 3
      window: 120s
    update_config:
      delay: 10s
      order: start-first
      parallelism: 1
    rollback_config:
      parallelism: 0
      order: stop-first
    state: present
    mode: replicated
    placement:
      constraints:
        - node.role == manager
