---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0775"
  with_items:
    - "{{ restic_data_dir }}"
    - "{{ restic_log_dir }}"

- name: Reformat dict to list
  ansible.builtin.set_fact:
    restic_backups: "{{ restic_backups | default([]) | map('extract', restic_backups) | list }}"
  when:
    - restic_backups

- name: Install restic
  ansible.builtin.include_tasks: ./install.yml

- name: Create backup script
  ansible.builtin.include_tasks: ./backup.yml
