---
- name: Install restic
  ansible.builtin.include_tasks: ./install.yml

- name: Initialize repositories
  ansible.builtin.include_tasks: ./configure.yml

- name: Create backup script
  ansible.builtin.include_tasks: ./backup.yml
