---
consul_servers: "\
  {% set _consul_servers = [] %}\
  {% for host in groups['consul_cluster'] %}\
    {% set _consul_node_role = hostvars[host]['consul_node_role'] | default('client', true) %}\
    {% if ( _consul_node_role == 'server' or _consul_node_role == 'both' ) %}\
      {% if _consul_servers.append(host) %}{% endif %}\
    {% endif %}\
  {% endfor %}\
  {{ _consul_servers }}"

_consul_lan_servers: "\
  {% set __consul_lan_servers = [] %}\
  {% for server in consul_servers %}\
    {% set _consul_datacenter = hostvars[server]['consul_datacenter'] | default('dc1', true) %}\
    {% if _consul_datacenter == consul_datacenter %}\
      {% if __consul_lan_servers.append(server) %}{% endif %}\
    {% endif %}\
  {% endfor %}\
  {{ __consul_lan_servers }}"
_consul_lan_servercount: "{{ (_consul_lan_servers | length) }}"

_retry_join: "\
  {% set __retry_join = [] %}\
  {% for server in _consul_lan_servers %}\
    {%   set _ = __retry_join.append(hostvars[server]['consul_advertise_address'] | default(hostvars[server]['consul_bind_address']) | default(hostvars[server]['ansible_default_ipv4']['address']) | mandatory) %}
  {% endfor %}\
  {{ __retry_join | map('ansible.utils.ipwrap') | list | to_json }}"

_is_server: "\
  {% set _consul_node_role = hostvars[inventory_hostname]['consul_node_role'] | default('client', true) %}\
  {{ ( _consul_node_role == 'server' or _consul_node_role == 'both' ) | bool }}"

_is_client: "\
  {% set _consul_node_role = hostvars[inventory_hostname]['consul_node_role'] | default('client', true) %}\
  {{ ( _consul_node_role == 'client' or _consul_node_role == 'both' ) | bool }}"
