---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0775"
  with_items:
    - "/home/system/stacks"

- name: Create network
  community.docker.docker_network:
    name: "{{ item }}"
    driver: "overlay"
  with_items:
    - traefik

- name: Deploy product stack file
  ansible.builtin.template:
    src: "{{ stack }}.yml.j2"
    dest: "/home/system/stacks/{{ stack }}.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Deploy stack from a compose file
  community.docker.docker_stack:
    state: present
    name: "{{ stack }}"
    compose:
      - "/home/system/stacks/{{ stack }}.yml"
