---
- name: restart timer
  ansible.builtin.systemd:
    name: "restic-{{ item.name | replace(' ', '') | string }}.timer"
    state: 'restarted'
    daemon_reload: true
    masked: false
  with_items: '{{ restic_backups }}'
  ignore_errors: true
  when:
    - item.name is defined
    - item.scheduled | default(false)