---
- name: Wait for 'config.yaml' to be created
  ansible.builtin.wait_for:
    path: "{{ docker_bazarr.config }}/config/config.yaml"
    state: present

- name: Update config.yaml file
  ansible.builtin.lineinfile:
    path: "{{ docker_bazarr.config }}/config/config.yaml"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - { regexp: '^auth:\s*apikey:\s*', line: 'auth:\n  apikey: "{{ secret_bazarr_api_key }}"' }
    - { regexp: '^general:\s*use_sonarr:\s*', line: 'general:\n  use_sonarr: true' }
    - { regexp: '^general:\s*use_radarr:\s*', line: 'general:\n  use_radarr: true' }
    - { regexp: '^general:\s*enabled_providers:\s*', line: 'general:\n  enabled_providers:\n    - opensubtitlescom\n    - tvsubtitles\n    - subf2m' }
    - { regexp: '^sonarr:\s*apikey:\s*', line: 'sonarr:\n  apikey: "{{ secret_sonarr_api_key }}"' }
    - { regexp: '^radarr:\s*apikey:\s*', line: 'radarr:\n  apikey: "{{ secret_radarr_api_key }}"' }
    - { regexp: '^opensubtitlescom:\s*username:\s*', line: 'opensubtitlescom:\n  username: "{{ secret_bazarr_opensubtitlescom_username }}"' }
    - { regexp: '^opensubtitlescom:\s*password:\s*', line: 'opensubtitlescom:\n  password: "{{ secret_bazarr_opensubtitlescom_password }}"' }
