---
- name: Wait for "config.yaml" to be created
  ansible.builtin.wait_for:
    path: "{{ docker_bazarr.config }}/config/config.yaml"
    state: present


- name: Replace auth.apikey with secret_bazarr_api_key
  ansible.builtin.replace:
    path: "{{ docker_bazarr.config }}/config/config.yaml"
    regexp: '^(auth:\n\s+apikey:).*'
    replace: '\1 {{ secret_bazarr_api_key }}'
    backup: yes

- name: Replace general.use_sonarr with true
  ansible.builtin.replace:
    path: "{{ docker_bazarr.config }}/config/config.yaml"
    regexp: '^(\s*use_sonarr:\s*)false'
    replace: '\1true'
    backup: yes

- name: Replace general.use_radarr with true
  ansible.builtin.replace:
    path: "{{ docker_bazarr.config }}/config/config.yaml"
    regexp: '^(\s*use_radarr:\s*)false'
    replace: '\1true'
    backup: yes

- name: Replace general.enabled_providers with list
  ansible.builtin.replace:
    path: "{{ docker_bazarr.config }}/config/config.yaml"
    regexp: '^(general:\n(\s+)enabled_providers:.*)'
    replace: '\1\n    - opensubtitlescom\n    - tvsubtitles\n    - subf2m'
    backup: yes

- name: Replace sonarr.apikey with secret_sonarr_api_key
  ansible.builtin.replace:
    path: "{{ docker_bazarr.config }}/config/config.yaml"
    regexp: '^(sonarr:\n\s+apikey:).*'
    replace: '\1 {{ secret_sonarr_api_key }}'
    backup: yes

- name: Replace radarr.apikey with secret_radarr_api_key
  ansible.builtin.replace:
    path: "{{ docker_bazarr.config }}/config/config.yaml"
    regexp: '^(radarr:\n\s+apikey:).*'
    replace: '\1 {{ secret_radarr_api_key }}'
    backup: yes

- name: Replace opensubtitlescom.username with secret_bazarr_opensubtitlescom_username
  ansible.builtin.replace:
    path: "{{ docker_bazarr.config }}/config/config.yaml"
    regexp: '^(opensubtitlescom:\n\s+username:).*'
    replace: '\1 {{ secret_bazarr_opensubtitlescom_username }}'
    backup: yes

- name: Replace opensubtitlescom.password with secret_bazarr_opensubtitlescom_password
  ansible.builtin.replace:
    path: "{{ docker_bazarr.config }}/config/config.yaml"
    regexp: '^(opensubtitlescom:\n\s+password:).*'
    replace: '\1 {{ secret_bazarr_opensubtitlescom_password }}'
    backup: yes

- name: Debug the content of config.yaml after update
  ansible.builtin.command: cat "{{ docker_bazarr.config }}/config/config.yaml"
  register: yaml_content_after
- ansible.builtin.debug:
    var: yaml_content_after.stdout_lines