---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0775
  with_items:
    - "{{ docker_scrutiny.config }}"
    - "{{ docker_scrutiny.data }}"

- name: Get disks
  ansible.builtin.shell: for line in $(lsblk --noheadings --list --scsi --output name); do echo "/dev/${line}:/dev/${line}"; done
  register: lsblk_disks
  changed_when: false

- name: Create network
  community.general.docker_network:
    name: "{{ item }}"
  with_items:
    - web

- name: Create and start container
  community.general.docker_container:
    name: scrutiny
    image: "{{ docker_scrutiny.image }}"
    pull: yes
    recreate: true
    volumes:
      - "{{ docker_scrutiny.config }}:/opt/scrutiny/config"
      - "{{ docker_scrutiny.data }}/influxdb2:/opt/scrutiny/influxdb"
      - "/run/udev:/run/udev:ro"
    devices: "{{ lsblk_disks.stdout_lines }}"
    networks:
      - name: homelab
        aliases:
          - scrutiny
    ports:
      - "{{ docker_port_scrutiny_http }}:8080"
    restart_policy: unless-stopped
    state: started
    capabilities:
      - SYS_RAWIO
      - SYS_ADMIN
    labels:
      homepage.group: Monitoring
      homepage.name: Scrutiny
      homepage.icon: scrutiny.svg
      homepage.href: http://{{ url_scrutiny }}
      homepage.description: Hard Drive S.M.A.R.T Monitoring
