---
consul_version: 1.19.1

consul_datacenter: "{{ datacenter_name }}"

consul_user: consul
consul_group: consul

consul_zip_url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_{{ arch[ansible_architecture] }}.zip"

consul_install_dir: /usr/bin
consul_config_dir: /etc/consul.d
consul_data_dir: /opt/consul

arch:
  x86_64: amd64
  aarch64: arm64
  armv7l: arm

consul_ports:
  dns: "8600"
  http: "8500"
  https: "8501"
  rpc: "8400"
  serf_lan: "8301"
  serf_wan: "8302"
  server: "8300"
  grpc: "8502"
  grpc_tls: "8503"

consul_bootstrap_expect_value: "{{ _consul_servers_servercount | int }}"
