---
- name: Configure UFW
  ansible.builtin.include_tasks: ufw.yml

- name: Install necessary packages
  ansible.builtin.apt:
    name:
      - nfs-kernel-server
      - samba
      - cifs-utils
    state: present
    update_cache: true

- name: Create the shared directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: "0755"
  loop: "{{ export_dirs }}"

- name: Configure NFS exports
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: "{{ item }} 192.168.2.0/24(rw,sync,no_root_squash,no_subtree_check)"
    create: true
  loop: "{{ export_dirs }}"

- name: Export the NFS shares
  ansible.builtin.command: exportfs -ra

- name: Ensure NFS server is running and enabled
  ansible.builtin.systemd:
    name: nfs-kernel-server
    state: started
    enabled: true

- name: Create Samba user
  ansible.builtin.command: "smbpasswd -a {{ samba_user }} {{ samba_password }}"
  args:
    creates: "/var/lib/samba/private/passdb.tdb"

- name: Add Samba configuration for shared directories
  ansible.builtin.blockinfile:
    path: /etc/samba/smb.conf
    block: |
      [{{ item | basename }}]
      path = {{ item }}
      browseable = yes
      read only = no
      guest ok = no
      valid users = {{ samba_user }}
  loop: "{{ export_dirs }}"

- name: Ensure Samba services are running and enabled
  ansible.builtin.systemd:
    name: smbd
    state: started
    enabled: true

- name: Ensure Samba services are running and enabled
  ansible.builtin.systemd:
    name: nmbd
    state: started
    enabled: true
