---
- name: Create directories
  ansible.builtin.file:
    path: "{{ docker_readarr.config }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0775

- name: Create and start container
  docker_container:
    name: readarr
    image: "{{ docker_readarr.image }}"
    image: linuxserver/readarr:0.2.3-develop
    network_mode: container:vpn
    pull: yes
    recreate: true
    image_name_mismatch: "recreate"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{ docker_readarr.config }}:/config"
      - "{{ docker_media_audiobooks }}:/data/audiobooks"
      - "{{ docker_media_ebooks }}:/data/books"
      - "{{ docker_media_comics }}:/data/comics"
      - "{{ docker_media_downloads }}:/downloads"
    networks:
      - name: homelab
        aliases:
          - readarr
    restart_policy: unless-stopped
    state: started
    labels:
      homepage.group: PVR
      homepage.name: Readarr
      homepage.icon: readarr.svg
      homepage.href: http://{{ url_readarr }}
      homepage.description: Ebook & Audiobook collection manager for Usenet and BitTorrent users
      homepage.widget.type: readarr
      homepage.widget.url: http://{{ host_poseidon_ip }}:{{ docker_port_readarr_http }}
      homepage.widget.key: "{{ secret_readarr_api_key }}"
    env:
      TZ: "{{ system_timezone }}"
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: ghcr.io/gilbn/theme.park:readarr
      TP_THEME: "{{ theme_park_theme }}"

- name: Settings Tasks
  ansible.builtin.include_tasks: "settings.yml"

#- name: VPN Tasks
#  ansible.builtin.include_tasks: "vpn.yml"
